export const assets = {
  "collection": {
    "speciesArtwork": "/assets/collection-species-artwork.png",
    "speciesArtwork1": "/assets/collection-species-artwork1.png",
    "speciesArtwork2": "/assets/collection-species-artwork2.png",
    "speciesArtwork3": "/assets/collection-species-artwork3.png",
    "iosSignal": "/assets/collection-ios-signal.svg",
    "iosWifiSignal": "/assets/collection-ios-wifi-signal.svg",
    "iosBatteryFull": "/assets/collection-ios-battery-full.svg",
    "search": "/assets/collection-search.svg",
    "bookOpen": "/assets/collection-book-open.svg",
    "plus": "/assets/collection-plus.svg",
    "bookOpen1": "/assets/collection-book-open1.svg"
  },
  "explore": {
    "photograph": "/assets/explore-photograph.png",
    "photograph1": "/assets/explore-photograph1.png",
    "photograph2": "/assets/explore-photograph2.png",
    "photograph3": "/assets/explore-photograph3.png",
    "iosSignal": "/assets/explore-ios-signal.svg",
    "iosWifiSignal": "/assets/explore-ios-wifi-signal.svg",
    "iosBatteryFull": "/assets/explore-ios-battery-full.svg",
    "mapPin": "/assets/explore-map-pin.svg",
    "chevronDown": "/assets/explore-chevron-down.svg",
    "check": "/assets/explore-check.svg",
    "trash2": "/assets/explore-trash2.svg",
    "bookOpen": "/assets/explore-book-open.svg",
    "plus": "/assets/explore-plus.svg",
    "bookOpen1": "/assets/explore-book-open1.svg"
  },
  "species": {
    "cyanotypeSpecimen": "/assets/species-cyanotype-specimen.png",
    "originalUnderwaterPhotograph": "/assets/species-original-underwater-photograph.png",
    "iosSignal": "/assets/species-ios-signal.svg",
    "iosWifiSignal": "/assets/species-ios-wifi-signal.svg",
    "iosBatteryFull": "/assets/species-ios-battery-full.svg",
    "arrowLeft": "/assets/species-arrow-left.svg",
    "chevronRight": "/assets/species-chevron-right.svg",
    "plus": "/assets/species-plus.svg"
  },
  "area": {
    "photograph": "/assets/area-photograph.png",
    "photograph1": "/assets/area-photograph1.png",
    "photograph2": "/assets/area-photograph2.png",
    "iosSignal": "/assets/area-ios-signal.svg",
    "iosWifiSignal": "/assets/area-ios-wifi-signal.svg",
    "iosBatteryFull": "/assets/area-ios-battery-full.svg",
    "mapPin": "/assets/area-map-pin.svg",
    "chevronDown": "/assets/area-chevron-down.svg",
    "check": "/assets/area-check.svg",
    "x": "/assets/area-x.svg",
    "locateFixed": "/assets/area-locate-fixed.svg",
    "search": "/assets/area-search.svg",
    "mapPin1": "/assets/area-map-pin1.svg",
    "check1": "/assets/area-check1.svg",
    "mapPin2": "/assets/area-map-pin2.svg"
  },
  "palau": {
    "photograph": "/assets/palau-photograph.png",
    "photograph1": "/assets/palau-photograph1.png",
    "photograph2": "/assets/palau-photograph2.png",
    "iosSignal": "/assets/palau-ios-signal.svg",
    "iosWifiSignal": "/assets/palau-ios-wifi-signal.svg",
    "iosBatteryFull": "/assets/palau-ios-battery-full.svg",
    "mapPin": "/assets/palau-map-pin.svg",
    "chevronDown": "/assets/palau-chevron-down.svg",
    "check": "/assets/palau-check.svg",
    "calendarDays": "/assets/palau-calendar-days.svg",
    "bookOpen": "/assets/palau-book-open.svg",
    "plus": "/assets/palau-plus.svg",
    "bookOpen1": "/assets/palau-book-open1.svg"
  },
  "turtle": {
    "underwaterPhotograph": "/assets/turtle-underwater-photograph.png",
    "iosSignal": "/assets/turtle-ios-signal.svg",
    "iosWifiSignal": "/assets/turtle-ios-wifi-signal.svg",
    "iosBatteryFull": "/assets/turtle-ios-battery-full.svg",
    "arrowLeft": "/assets/turtle-arrow-left.svg",
    "shield": "/assets/turtle-shield.svg",
    "eye": "/assets/turtle-eye.svg",
    "circleX": "/assets/turtle-circle-x.svg",
    "hand": "/assets/turtle-hand.svg",
    "arrowUp": "/assets/turtle-arrow-up.svg"
  },
  "note": {
    "underwaterPhotograph": "/assets/note-underwater-photograph.png",
    "iosSignal": "/assets/note-ios-signal.svg",
    "iosWifiSignal": "/assets/note-ios-wifi-signal.svg",
    "iosBatteryFull": "/assets/note-ios-battery-full.svg",
    "arrowLeft": "/assets/note-arrow-left.svg",
    "shapes": "/assets/note-shapes.svg",
    "eye": "/assets/note-eye.svg",
    "layers": "/assets/note-layers.svg",
    "camera": "/assets/note-camera.svg",
    "hand": "/assets/note-hand.svg",
    "minusCircle": "/assets/note-minus-circle.svg"
  }
} as const;
